services:
  web: 
    build: 
      context: web
    volumes:
      - ./web:/app
    ports:
      - "5002:8505"
    networks:
      - postgres

  postgres_data:
    build:
      context: postgres_data
    volumes:
      - ./postgres_data:/app
    networks:
      - postgres

  api:
    build:
      context: api
    volumes:
      - ./api:/app
    ports:
      - "5001:5000"
    networks:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
       - ./postgres_data:/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: psylook@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: